name = "FermiHarmonics"
uuid = "e57e2ec9-1d44-475a-849e-67b77bc2896e"
version = "0.1.0"
authors = ["jackhfarrell"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
HOHQMesh_jll = "1d5cbd98-5122-5a8a-bea1-c186d986ee7f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
ArgParse = "1.2.0"
CairoMakie = "0.15"
Dates = "1.10"
DrWatson = "2.19"
HDF5 = "0.17.2"
HOHQMesh = "0.2"
HOHQMesh_jll = "1.5.1"
Interpolations = "0.16.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.10"
Logging = "1"
LoggingExtras = "1.2.0"
NLsolve = "4"
Parameters = "0.12.3"
Plots = "1.41.4"
Printf = "1.10"
SciMLBase = "2"
Sockets = "1"
SparseArrays = "1.10"
StaticArrays = "1.9"
Statistics = "1"
TOML = "1"
Trixi = "0.13.20"
WriteVTK = "1.21"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
